### ISSUE TITLE
data name

### ISSUE THREAD

**Issue by geek-APTX4869** [feifeiobama/OrthogonalDet#12]
Dear author：
  `datasets/ImageSets/Main/IOD/trainval.txt`的内容为名称如`000005`，缺少年份如`2012_000005`

**Comment by feifeiobama** [comment]
Please download PASCAL VOC 2007. We only mentioned it in our [supplementary material](https://openaccess.thecvf.com/content/CVPR2024/supplemental/Sun_Exploring_Orthogonality_in_CVPR_2024_supplemental.pdf), sorry for that.
