### ISSUE TITLE
AssertionError: Dataset 'my_train' is empty!

### ISSUE THREAD

**Issue by Melleaa** [feifeiobama/OrthogonalDet#6]
Hello！I am a student who recently started learning open-world object detection. I want to know how I should implement moving all images to datasets/JPEGImages and annotations to datasets/Annotations. Specifically, what should the file paths look like in order to resolve this assertion error? Thank you！

**Comment by feifeiobama** [comment]
~~You can take a look at step 2 in https://github.com/scuwyh2000/RandBox/blob/main/GETTING_STARTED.md, which may resolve your problem. If the error persists, I will provide more details on how to organize the folder.~~

**Comment by Melleaa** [comment]
Thank you for your reply! I try to organize the folder like this:
C:\Users\14847\Project\OrthogonalDet-main\datasets\t1\images\train, as same as step 2 of RandBox 
or
C:\Users\14847\Project\OrthogonalDet-main\datasets\JPEGImages\train, as stated in your README.md,
then I run the script run_owod.sh under WSL configured with Ubuntu 20.04,but this error still persists in both of these cases.
Could you please show me more details? Thank you!
Here's the error message:
![error_info](https://github.com/user-attachments/assets/a6ea7f02-cce0-413e-8548-49131bf6fbd9)

**Comment by feifeiobama** [comment]
Sorry I made a mistake earlier. Moving all images to `C:\Users\14847\Project\OrthogonalDet-main\datasets\JPEGImages` should work fine, see below: https://github.com/feifeiobama/OrthogonalDet/blob/ad8e12b180d87a7d0cda5f30d94aa9538ad8d947/core/pascal_voc.py#L124

**Comment by wwylvswy** [comment]
This is my directory structure. I created the directory /datasets/JPEGImages myself. 
![image](https://github.com/user-attachments/assets/c992b3e5-d8f7-4bdc-a746-da7ebc28cd10)
 I downloaded the following datasets.
```
PASCAL2007+2012: trian+val
PASCAL2007 test
COCO2017: train+val
```
After extracting annotations_trainval2017.zip, I ran coco_to_voc.py to convert it to VOC format. Running the coco_to_voc.py script directly in the project would generate /datasets/Annotations/Annotations, so I modified the targets_path in the code.
```
# previous
target_folder = "datasets/Annotations" 
# fixed
target_folder = "datasets"
```
Then extracted PASCAL datasets, and then moved all PASCAL annotation files to /datasets/Annotations.
All images should be placed in the /datasets/JPEGImages directory.

**Comment by Melleaa** [comment]
Thank you for your reply! I forgot to extract PASCAL! After moving all PASCAL images and annotations into datasets/JPEGImages and datasets/Annotations, it works fine! Thank you!

**Comment by eightnight2049** [comment]
> 这是我的目录结构。我自己创建了目录 /datasets/JPEGImages。 ![image](https://github.com/user-attachments/assets/c992b3e5-d8f7-4bdc-a746-da7ebc28cd10)我下载了以下数据集。
> 
> ```
> PASCAL2007+2012: trian+val
> PASCAL2007 test
> COCO2017: train+val
> ```
> 
> 提取annotations_trainval2017.zip后，我运行 coco_to_voc.py 将其转换为 VOC 格式。直接在项目中运行 coco_to_voc.py 脚本将生成 /datasets/Annotations/Annotations，因此我在代码中修改了targets_path。
> 
> ```
> # previous
> target_folder = "datasets/Annotations" 
> # fixed
> target_folder = "datasets"
> ```
> 
> 然后提取 PASCAL 数据集，然后将所有 PASCAL 注释文件移动到 /datasets/Annotations。所有图像都应放在 /datasets/JPEGImages 目录中。

Hello, I am running this code myself and I have some questions about the dataset. Are these the four datasets we need?
> PASCAL2007+2012: train+val
> PASCAL2007 test
> COCO2017: train+val
I was previously these three:
> PASCAL2007+2012: train+val
> COCO2017: train+val
Currently, the number of images and annotations I have are: 150,375 images, and the number of XML annotations is 149,306.
I want to know if this number is correct.
